### ISSUE TITLE
CompositeStreamStrategy looks strange

### ISSUE THREAD

**Issue by DariusL** [commonsguy/cwac-provider#12]
I was just reading your code when I saw something strange [here](https://github.com/commonsguy/cwac-provider/blob/master/provider/src/main/java/com/commonsware/cwac/provider/CompositeStreamStrategy.java#L113). `CompositeStreamStrategy.update` calls `canDelete`. Looks like a code copying issue, but if this code is correct, you should probably comment it.

**Comment by commonsguy** [comment]
No, that's a bug. Since I'm not supporting update/delete anywhere, those hooks are not tested. I'll fix it tomorrow. Thanks!

**Comment by commonsguy** [comment]
Addressed in v0.4.1 -- thanks again!
