### ISSUE TITLE
SecurityException on Android 4.3

### ISSUE THREAD

**Issue by timautin** [commonsguy/cwac-provider#19]
I'm using StreamProvider to start a MediaStore.ACTION_IMAGE_CAPTURE intent.

Here is the provider definition:

```
<provider
    android:name="com.commonsware.cwac.provider.StreamProvider"
    android:authorities="my.app.package.name.ShareFileProvider"
    android:exported="false"
    android:grantUriPermissions="true">
    <meta-data
        android:name="com.commonsware.cwac.provider.STREAM_PROVIDER_PATHS"
        android:resource="@xml/file_paths"/>
</provider>
```

And here is how I start the intent:

```
Uri uri = StreamProvider.getUriForFile(getApplicationContext().getPackageName() + ".ShareFileProvider", destination);

Intent intent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
intent.putExtra(MediaStore.EXTRA_OUTPUT, uri);
startActivityForResult(intent, REQUEST_TAKE_PHOTO);
```

On Android 7.1.1, it works fine. But on Android 4.3, the photo app crashes with a SecurityException (Permission Denial: opening provider com.commonsware.cwac.provider.StreamProvider [...] that is not exported from [...]). If I export the provider, my app crashes, saying that this provider must not be exported.

Is it normal? To avoid the crash, I added a check to use the old Uri.fromFile function if Android version is lower than 24, is it fine? I'd prefer to have the StreamProvider working for all versions.

**Comment by commonsguy** [comment]
Um, this is an issue tracker, not a support board. In the future, please [follow the instructions for getting support](https://github.com/commonsguy/cwac-provider#questions).

> Is it normal? 

It should be crashing on 7.1.1 too, with the same `SecurityException`. Nobody has rights to work with your `Uri` values, unless you grant those rights.

Usually, this would be by adding `FLAG_GRANT_READ_URI_PERMISSION` and/or `FLAG_GRANT_WRITE_URI_PERMISSION` to the `Intent`. However, mostly, that affects the data of the `Intent` (e.g., `setData()`, `setDataAndType()`). On older Android versions, it does not automatically affect extras. In [this blog post](https://commonsware.com/blog/2016/08/31/granting-permissions-uri-intent-extra.html), I outline the approach for granting rights to a `Uri` in extras. And in [this sample app](https://github.com/commonsguy/cw-omnibus/tree/master/Camera/FileProvider), I demonstrate using `FileProvider` with `ACTION_IMAGE_CAPTURE`. `StreamProvider` would work similarly.

In general, with the buggy world of camera apps, you might consider keeping your `targetSdkVersion` below 24 and always using `Uri.fromFile()`, until 2020 or thereabouts. Google's own camera app did not support `content` schemes until this summer, and I would imagine that many other camera apps will choke on a `content` `Uri`.

**Comment by timautin** [comment]
Thanks for the fast and accurate answer! Sorry for posting here, I thought it may have been a bug

For 7.1.1, it works, and _if the Android doc is accurate_, we don't need to grant write permission : [https://developer.android.com/training/camera/photobasics.html](url) (see the 2nd implementation of the dispatchTakePictureIntent function).

For 4.3, it works when adding the permissions, thanks a lot!

I'm not the guy who decides the target SDK, so I'll leave my if condition and use Uri.fromFile on Android < 24.

Thanks again!

**Comment by commonsguy** [comment]
I cannot explain how this works on 7.1.1 without a permission grant. Frankly, that scares the hell out of me, and I will need to do some investigations. Thanks for pointing it out!

**Comment by timautin** [comment]
Well, I just tested it again to be sure and I can confirm that it works. It may be related to what Ian Lake talked about in this post [http://stackoverflow.com/questions/39213790/sharing-video-text-with-fileprovider-causes-permission-denial-exception/39214019?noredirect=1#comment65767052_39214019](url) for the ACTION_SEND intent.

But again, on the Android doc, the permission is not added in the sample code.

**Comment by commonsguy** [comment]
Ah, I understand. The change they added in Android 5.0, that I mentioned in my blog post, not only uses `setClipData()` to ensure that flags affect the `Uri`, but they also add `FLAG_GRANT_READ_URI_PERMISSION` and `FLAG_GRANT_WRITE_URI_PERMISSION` forcibly to the `Intent`. So, their code would work on Android 5.0 or higher, due to some undocumented changes.

**Comment by timautin** [comment]
Alright, thanks for the clarification!
