### ISSUE TITLE
test.pdf is of invalid format

### ISSUE THREAD

**Issue by galenhuntington** [commonsguy/cwac-provider#21]
I've been getting errors like this whenever I try to view a pdf file from the assets directory.  I've reproduced on different devices on both Marshmallow and Nougat (the latter a Nexus 6P on NBD91K).  I got this error both in my code and in the demo app, which I didn't alter other than adding missing width/height attributes to an xml file.

I'm not an Android expert, but from the logs it looks like the Android pdf viewer is trying to do an ioctl call on a socket (`ioctlcmd=7704`, which I think is `ashmem_get_size_region`) which is not supported.

It's possible the pdf viewer cannot be persuaded to not make this call and will never work on a stream.  Or maybe there's something with how the stream is being passed that causes this, or something that can be done to work around it.  I for one am stymied.

**Comment by commonsguy** [comment]
What PDF viewer are you using?

I just ran some tests with the demo app. Adobe Reader, ezReader, and Amazon Kindle are perfectly content with the demo app. Drive (on a 6P) and Foxit are unhappy. So, I'm reasonably comfortable that the problem lies more on the client side -- if I were screwing up in general, I would expect all of these to fail.

Overall, there's only so much I can do, though I'll poke at logs for those two and see if there's anything that gives me clues. If you tell me what PDF viewer you are using (if it's not one of those), I can peek at it too.

**Comment by galenhuntington** [comment]
Thanks for responding!

I didn't install a pdf viewer, and Google Drive was (at least for me) already present by default, and so it goes straight to it without asking.  I haven't tried any others.

The file is streamed correctly:  When I change the content type to text/plain, I can view in a text editor and it looks like a pdf file.  So it does seem to be a client issue.

So I guess the question is whether there is a way to convince Google Drive (and any others with issues) to accept a stream.  The answer may be no, which would be unfortunate, as telling users they have to install a supported pdf viewer is not optimal.

**Comment by commonsguy** [comment]
Well, Drive seems OK with `FileProvider`. So, it's not a general `ContentProvider` issue.

It may be a few days before I get a chance to poke at this. If you want to try an experiment, manually copy your PDF file to the root of external storage, then tweak your metadata to use `<external-path>` instead of `<asset>`. If Drive is happy now, then the issue may be tied to the content not coming from a regular file. If Drive is still unhappy, then it's more likely that there's a bug somewhere in `StreamProvider` (as I should be able to handle `<external-path>` as well as `FileProvider` does).

**Comment by galenhuntington** [comment]
I tried basically what you suggest:  I used <external-files-path> and had the app copy the file to getExternalFilesDir(null) (actually, to a subdirectory of it since the name attribute seemed to have to be nonempty).  Drive was happy and displayed the file correctly.

So it does seem to hinge on whether it's a regular file, which is not surprising given the ioctl call error in the logs.

**Comment by commonsguy** [comment]
My working theory is that Drive (and perhaps Foxit) are trying to seek the stream or do something low-level on the stream in native code that is equally unsupported. I am fairly certain that there's not a lot that I can do about that other than education (e.g., filing bug reports), though I will check again to see if somebody has an option.

AFAIK, the only way to create a stream that these apps will like is to do so from an actual file. That doesn't just break `StreamProvider` but anything else that does not stream a file directly (e.g., it's a file, but it's encrypted, and we need to decrypt the data on the fly as part of streaming it).

I'll keep this issue open, mostly for tracking what I'm doing on the research and (presumably) education front.

**Comment by commonsguy** [comment]
> from the logs it looks like the Android pdf viewer is trying to do an ioctl call on a socket (ioctlcmd=7704, which I think is ashmem_get_size_region) which is not supported

If you are able to reproduce this, could you paste your LogCat into a comment on the issue? While I can reproduce the problem, I am not seeing an `ioctl` reference. What I see is:

```
11-20 19:17:59.133 901-921/? I/ActivityManager: Displayed com.google.android.apps.docs/com.google.android.apps.viewer.PdfViewerActivity: +468ms
11-20 19:17:59.157 5971-5983/? D/pdf_document_jni: Set copy mode 1
11-20 19:17:59.157 5971-5983/? D/pdf_document_jni: Creating FPDF_DOCUMENT from fd: 35
11-20 19:17:59.164 5971-5983/? E/apps/viewer/android/foxit/document.cc: Parse Document failed (err=3).
11-20 19:17:59.250 901-3173/? D/WindowManager: relayoutVisibleWindow: Window{756123d u0 com.commonsware.cwac.provider.demo/com.commonsware.cwac.provider.demo.MainActivity EXITING} mAnimatingExit=true, mRemoveOnExit=false, mDestroying=false
11-20 19:17:59.332 901-921/? I/WindowManager: Destroying surface Surface(name=Starting com.google.android.apps.docs) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.removeLocked:1449 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2478 com.android.server.wm.AppWindowToken.destroySurfaces:365 com.android.server.wm.WindowStateAnimator.finishExit:565 com.android.server.wm.WindowStateAnimator.stepAnimationLocked:491 com.android.server.wm.WindowAnimator.updateWindowsLocked:303 
11-20 19:17:59.839 901-911/? I/ActivityManager: Killing 5519:com.qualcomm.timeservice/1000 (adj 906): empty #17
11-20 19:17:59.876 901-5005/? D/ActivityManager: cleanUpApplicationRecord -- 5519
11-20 19:17:59.927 566-566/? I/ServiceManager: Waiting for service AtCmdFwd...
11-20 19:18:00.018 901-914/? I/ActivityManager: Killing 4651:com.google.android.calendar/u0a36 (adj 906): empty #17
11-20 19:18:00.024 901-2728/? I/ActivityManager: Killing 5971:com.google.android.apps.docs/u0a43i0 (adj 0): isolated not needed
11-20 19:18:00.028 901-3212/? I/WindowManager: Destroying surface Surface(name=com.google.android.apps.docs/com.google.android.apps.viewer.PdfViewerActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.removeLocked:1449 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2478 com.android.server.wm.WindowManagerService.removeWindowLocked:2436 com.android.server.wm.WindowManagerService.removeWindowLocked:2305 com.android.server.wm.WindowManagerService.removeWindow:2300 com.android.server.wm.Session.remove:193 
```

(that's from a Nexus 6P and my `demo/` app, trying to view the 20KB PDF)

What's interesting about my log is that the error is coming from `/apps/viewer/android/foxit/document.cc`, suggesting that Google licensed Foxit's PDF rendering engine. That might explain why Foxit fails as well.

**Comment by commonsguy** [comment]
Curiously, Foxit's own MobilePDF app does not appear to use the same code. It gives a Java-level stack trace:

```
11-21 08:19:18.348 8042-8042/? W/System.err: java.io.FileNotFoundException: Not a whole file
11-21 08:19:18.356 8042-8042/? W/System.err:     at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:852)
11-21 08:19:18.356 8042-8042/? W/System.err:     at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:789)
11-21 08:19:18.356 8042-8042/? W/System.err:     at com.fuxin.read.RD_ReadActivity.a(Unknown Source)
11-21 08:19:18.356 8042-8042/? W/System.err:     at com.fuxin.read.RD_ReadActivity.b(Unknown Source)
11-21 08:19:18.356 8042-8042/? W/System.err:     at com.fuxin.read.RD_ReadActivity.a(Unknown Source)
11-21 08:19:18.356 8042-8042/? W/System.err:     at com.fuxin.app.plat.FxFragmentActivity.onMAMCreate(Unknown Source)
11-21 08:19:18.356 8042-8042/? W/System.err:     at com.microsoft.intune.mam.client.app.offline.OfflineActivityBehavior.onCreate(Unknown Source)
11-21 08:19:18.356 8042-8042/? W/System.err:     at com.microsoft.intune.mam.client.support.v4.app.MAMFragmentActivity.onCreate(Unknown Source)
11-21 08:19:18.356 8042-8042/? W/System.err:     at android.app.Activity.performCreate(Activity.java:6664)
11-21 08:19:18.356 8042-8042/? W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
11-21 08:19:18.356 8042-8042/? W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
11-21 08:19:18.356 8042-8042/? W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
11-21 08:19:18.357 8042-8042/? W/System.err:     at android.app.ActivityThread.-wrap12(ActivityThread.java)
11-21 08:19:18.357 8042-8042/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
11-21 08:19:18.357 8042-8042/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
11-21 08:19:18.357 8042-8042/? W/System.err:     at android.os.Looper.loop(Looper.java:154)
11-21 08:19:18.357 8042-8042/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6077)
11-21 08:19:18.357 8042-8042/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
11-21 08:19:18.357 8042-8042/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
11-21 08:19:18.357 8042-8042/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

This would fit if they called `openFileDescriptor()` on `ContentResolver` asking for a `rw` mode. PDF viewers need to gracefully degrade to getting read-only access if read-write access is unavailable.

I filed an issue with Foxit on this.

**Comment by commonsguy** [comment]
I have filed an in-app feedback report for Drive regarding the Drive PDF Viewer crash. I will write a blog post warning about making assumptions about streams tomorrow. And, at the moment, that's pretty much all I can do.

**Comment by galenhuntington** [comment]
Well for the record I tried all sorts of things and could not reproduce that ioctl error, which I saw several times before.  So my guess is that a different process must have been spitting that out.  I'm now only seeing the same error as you.  Sorry about the red herring!
