### ISSUE TITLE
Cannot import: " Failed to resolve: com.commonsware.cwac:provider:0.5.0"

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [commonsguy/cwac-provider#25]
I've added just what the repo page says:

```
buildscript {
    repositories {
      ...
        maven {
            url "https://s3.amazonaws.com/repo.commonsware.com"
        }
    }
```

```
dependencies {
    ...
    compile 'com.commonsware.cwac:provider:0.5.0'
}
```

Yet I get an error:

> Error:(29, 13) Failed to resolve: com.commonsware.cwac:provider:0.5.0
> <a href="openFile:C:/Users/User/AndroidStudioProjects/MyApplication2/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

I also tried "releaseCompile" instead (as the demo shows), but it still doesn't work. How come?

Here's how it all look like:

![untitled](https://cloud.githubusercontent.com/assets/5357526/22459063/c3f6daca-e7a7-11e6-9b4b-bae5dbd69204.png)

**Comment by AndroidDeveloperLB** [comment]
Seems moving this part:

```
repositories {
    maven {
        url "https://s3.amazonaws.com/repo.commonsware.com"
    }
}
```

to the gradle file on the right has fixed it. How come?

**Comment by shtolik** [comment]
If you'll move that repo to allprojects part of main build.gradle it will also work
allprojects {
    repositories {
        jcenter()
        maven {
            url "https://s3.amazonaws.com/repo.commonsware.com"
        }
    }
}

buildscript part is probably only for initial setup of gradle project. and then all modules are getting dependencies from repositories defined in allprojects parts

**Comment by AndroidDeveloperLB** [comment]
ok sorry. thanks.

**Comment by assifgit** [comment]
It works,
I forget to include the
repositories {
    maven {
        url "https://s3.amazonaws.com/repo.commonsware.com"
    }
}

in Manifest.

**Comment by AndroidDeveloperLB** [comment]
Manifest? You probably mean gradle file...
And it doesn't work. I don't see any commit to the release to make it work with what you wrote now.
