### ISSUE TITLE
Proguard for StreamProvider

### ISSUE THREAD

**Issue by frakc** [commonsguy/cwac-provider#27]
Which configuration for proguard we should use for .StreamProvider?

**Comment by commonsguy** [comment]
This is an issue tracker, not a support board. Please follow [the instructions for getting support](https://github.com/commonsguy/cwac-provider#questions).

Since the library is fairly tiny (22KB JAR), the simplest solution is to keep everything in the `com.commonsware.cwac.provider` package.
