### ISSUE TITLE
Sending image from asset to many apps doesn't work on Android 7.1, yet work on Android 6.0.x

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [commonsguy/cwac-provider#28]
I've added a webP image (and also png and jpg), to the sample.

I've updated the code to support it, by editing the string-array called "assets" , and editing the  "ASSET_PATHS" to have the path to the file, like the others.

The sample succeeds to share the file to WhatsApp and Viber only on Android 6.x and below, but not on Android 7.1.1 . There, it becomes black.
However, on Hangouts it works fine on all Android versions

How could this be?
Maybe for this, I should use resource instead of assets?

**Comment by commonsguy** [comment]
> How could this be?

I have no way of knowing, as you have not followed [the instructions for filing bug reports](https://github.com/commonsguy/cwac-provider/blob/master/CONTRIBUTING.md#contributing-bug-reports).

> Maybe for this, I should use resource instead of assets?

I doubt that this will improve matters. Plus, I plan on deprecating raw resource support (see issue #26).

**Comment by AndroidDeveloperLB** [comment]
Here:

## the Android OS version on which you are experiencing the problem
Android 7.1.1.

## the code necessary to reproduce the problem (this could be the repo's demo app, or it could be some demo project of yours that you publish)
The sample. Just add an image, and update it:

**MainActivity.java**
```
...
    private static final String[] ASSET_PATHS = {
...
            "assets/some_image.webP",
    };


```

**arrays.xml**

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
  <string-array name="assets">
...
    <item>webp</item>
  </string-array>
</resources>
```

## the steps necessary, using that code and that version of Android, to reproduce the problem
Run the app while trying to share the image. Choose either WhatsApp or Viber.
Try it on Android 7.1.1 and on 6.0.x .
On 7.1.1 , it will show a black image, and on 6.0.x it will show the image.

**Comment by commonsguy** [comment]
The instrumentation tests test PNG files as assets, and they work fine on Android 7.1.1 (tested on a Nexus 9). I can read the same bytes that are in the actual assets themselves.

Take your image, upload it somewhere on the test device, and change your XML to point to that particular location. IOW, serve a file, instead of serving an asset. Then, try that with your test clients.

If this works, then my best guess is that the test clients are trying to seek on the stream on Android 7.1.1 whereas they are not on Android 6.0. I do not know why that behavior would change, and [streams served from assets and raw resources are non-seekable by nature](https://commonsware.com/blog/2016/11/21/consuming-content-be-flexible.html). The only way that I have thought of to address this would be to create cached copies of assets as files, so we can serve the files -- see issue #29.

If, however, even serving your images as files fails, then something else is wrong. See if there are any error messages/stack traces in LogCat coming from the client app that might provide clues.

**Comment by AndroidDeveloperLB** [comment]
I tried PNG files. It didn't work. I tested on Nexus 5x with 7.1.1 .
I don't understand your new instructions. Which XML ? The sample code doesn't have an XML to point to image. It is in the Java file, and that's what I already did.
Haven't I used it correctly, like the other files you've allowed to share?

Anyway, here's the full project. Please try it while trying to send to WhatsApp or Viber :
https://ufile.io/5d1021
Can you please tell me what I'm doing wrong?

**Comment by commonsguy** [comment]
> Which XML ?

The XML in your app that configures the behavior of `StreamProvider`. For example, in the `demo/` app, that is [`res/xml/paths.xml`](https://github.com/commonsguy/cwac-provider/blob/master/demo/src/main/res/xml/paths.xml).

> Please try it while trying to send to WhatsApp or Viber :

I use neither app. I would rather not unnecessarily sign up for services that I will not use.

**Comment by AndroidDeveloperLB** [comment]
The issue is when using those apps, but only on Android 7.1.1.
Both WhatsApp and Viber are very popular apps, which should be able to share images.
I need to share an image from within the app to both of them, and to any other app too.
I've tested it with other chat apps, such as Telegram and Allo, and it worked fine.
Only with WhatsApp and Viber I see these issues, but they are very popular to avoid supporting them.

About the "paths.xml", what should I change there? It already has the assets handling there being enabled:

`	<asset name="assets" path="test" />`

Have you looked at the project? What is wrong with what I did there?

**Comment by commonsguy** [comment]
> what should I change there?

Change it to serve a file, from wherever you choose to upload your image onto your test device. As [I wrote previously](https://github.com/commonsguy/cwac-provider/issues/28#issuecomment-277684468), "IOW, serve a file, instead of serving an asset. Then, try that with your test clients."

So, for example, if you copy your image into `Documents` on external storage of your test device, you could add this element to your XML:

    <external-files-path dir="Documents" name="test-external-files"/>

Then, construct a `File` object pointing to your uploaded image, and use `StreamProvider.getUriForFile()` to get a `Uri` to that `File` as served by `StreamProvider`. Use that `Uri` with your `ACTION_SEND` request, instead of one pointing to the asset. Test that with your four apps (WhatsApp, Viber, Telegram, Allo).

> Have you looked at the project?

No.

> What is wrong with what I did there?

Probably nothing. If, on the same device, with the same app installation, Telegram and Allo work, but WhatsApp and Viber do not, your app code is fine, as far as it goes.

**Comment by AndroidDeveloperLB** [comment]
But if I share a file, what's the difference between using StreamProvider, and the support library's FileProvider? I would still need to copy the file from the app, into the storage, and having 2 copies of the file this way.
Why does it matter if it's a file outside of the APK, and a file within ? I thought it doesn't matter, as the provider itself sends the content to the app that gets it...
I don't understand why it shouldn't work.

**Comment by commonsguy** [comment]
> But if I share a file, what's the difference between using StreamProvider, and the support library's FileProvider? 

Nothing. This is an experiment, to determine whether a known category of problems (non-seekable streams from assets) is the source of your difficulty.

> I don't understand why it shouldn't work.

The only IPC streams that are seekable (i.e., client can rewind the stream) are those created with files as the source of the stream data. Assets are not files on the device. Resources are also not files on the device. Some clients insist upon seekable streams (see issue #21), and for those, assets (and raw resources) are not suitable data sources, unless I make changes (see issue #29).

So, we need to determine if WhatsApp or Viber are trying to use seekable streams.

Now, that might be apparent from log messages that WhatsApp/Viber log when they try using your existing code. So, you might just re-try your existing experiment and update the issue with the log messages from those apps around the time that you tried sending them the `Uri`, and perhaps I'll see something that points me in a direction as to why those apps are failing.

Otherwise, the experiment that I described -- temporarily switching from assets to files -- will determine whether the issue is seekable streams or not.

**Comment by AndroidDeveloperLB** [comment]
ok, about WhatsApp, I got this warning in the logs:

> 02-06 17:05:04.379 24590-24590/com.whatsapp W/Bundle: Key android.intent.extra.STREAM expected ArrayList but value was a android.net.Uri$HierarchicalUri.  The default value <null> was returned.
> 02-06 17:05:04.382 24590-24590/com.whatsapp W/Bundle: Attempt to cast generated internal exception:
>                                                       java.lang.ClassCastException: android.net.Uri$HierarchicalUri cannot be cast to java.util.ArrayList
>                                                           at android.os.Bundle.getParcelableArrayList(Bundle.java:916)
>                                                           at android.content.Intent.getParcelableArrayListExtra(Intent.java:6357)
>                                                           at com.whatsapp.ContactPicker.k(ContactPicker.java:618)
>                                                           at com.whatsapp.ContactPicker.onCreate(ContactPicker.java:360)
>                                                           at android.app.Activity.performCreate(Activity.java:6688)
>                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
>                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2633)
>                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2741)
>                                                           at android.app.ActivityThread.-wrap12(ActivityThread.java)
>                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
>                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                           at android.os.Looper.loop(Looper.java:154)
>                                                           at android.app.ActivityThread.main(ActivityThread.java:6169)
>                                                           at java.lang.reflect.Method.invoke(Native Method)
>                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
>                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)

For Viber, I got a very similar warning in the logs:

> 02-06 17:07:10.044 29295-29295/com.viber.voip W/Bundle: Key android.intent.extra.STREAM expected ArrayList but value was a android.net.Uri$HierarchicalUri.  The default value <null> was returned.
> 02-06 17:07:10.048 29295-29295/com.viber.voip W/Bundle: Attempt to cast generated internal exception:
>                                                         java.lang.ClassCastException: android.net.Uri$HierarchicalUri cannot be cast to java.util.ArrayList
>                                                             at android.os.Bundle.getParcelableArrayList(Bundle.java:916)
>                                                             at android.content.Intent.getParcelableArrayListExtra(Intent.java:6357)
>                                                             at com.viber.voip.util.af.f(SourceFile:156)
>                                                             at com.viber.voip.util.af.a(SourceFile:106)
>                                                             at com.viber.voip.HomeActivity.i(SourceFile:487)
>                                                             at com.viber.voip.HomeActivity.onCreate(SourceFile:317)
>                                                             at android.app.Activity.performCreate(Activity.java:6688)
>                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
>                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2633)
>                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2741)
>                                                             at android.app.ActivityThread.-wrap12(ActivityThread.java)
>                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
>                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                             at android.os.Looper.loop(Looper.java:154)
>                                                             at android.app.ActivityThread.main(ActivityThread.java:6169)
>                                                             at java.lang.reflect.Method.invoke(Native Method)
>                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
>                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)

I don't think there are other logs that can be useful

**Comment by commonsguy** [comment]
Those errors suggest that you are using `ACTION_SEND_MULTIPLE`, but are only passing a single `Uri`.

**Comment by AndroidDeveloperLB** [comment]
I used the sample of this repo. I think it should work, no?
About the file on the website, you have a counter. Have you waited 5 seconds? You are supposed to wait 5 seconds and then click it.

**Comment by commonsguy** [comment]
>I used the sample of this repo

Then if those stack traces are correct, there are bugs in WhatsApp and Viber. The `demo/` app [uses `ACTION_SEND`](https://github.com/commonsguy/cwac-provider/blob/v0.5.0/demo/src/main/java/com/commonsware/cwac/provider/demo/MainActivity.java#L97). Both apps are calling `getParcelableArrayListExtra()` for `EXTRA_STREAM`. Those *should* fail for `EXTRA_STREAM` on `ACTION_SEND`, as `EXTRA_STREAM` is supposed to provide a single `Uri`, not an `ArrayList<Uri>`. `getParcelableArrayListExtra()` is the proper call for `ACTION_SEND_MULTIPLE`, not `ACTION_SEND`.

At this point, I am closing this issue, as I have no current evidence that this represents some problem in this library. If WhatsApp or Viber have developer support, you might contact them and provide your stack traces.

> Have you waited 5 seconds?

Yes. I then click the button. It turns into a checkmark, the page reloads, and I'm back to the 5-second countdown.

**Comment by AndroidDeveloperLB** [comment]
So what can I do to make it work there too? They won't answer, as I've tried in the past for other reasons.
Maybe I can send the intent differently for them?
About the download link, for me it works fine on another PC. 
Here, attached here instead.
[5d1021-cwac-provider.zip](https://github.com/commonsguy/cwac-provider/files/756074/5d1021-cwac-provider.zip)

**Comment by commonsguy** [comment]
If I were in your shoes, I would temporarily modify my app to either:

- Stick with `ACTION_SEND`, but put an `ArrayList<Uri>` in `EXTRA_STREAM`, rather than a plain `Uri`; or
- Switch to `ACTION_SEND_MULTIPLE`, and put an `ArrayList<Uri>` in `EXTRA_STREAM`

See whether WhatsApp and Viber are now happy. If they are, you have isolated the problem, and you can see if you can figure out how to modify your app to apply this hack for those apps but follow the `ACTION_SEND` spec for everyone else.

**Comment by AndroidDeveloperLB** [comment]
ok, I tried the ArrayList<Uri>, but it didn't work (closed WhatsApp and shows black image for Viber) . Here's the log:

>                                                             Caused by: java.lang.SecurityException: Permission Denial: opening provider com.commonsware.cwac.provider.StreamProvider from ProcessRecord{9405e93 12914:com.whatsapp/u0a210} (pid=12914, uid=10210) that is not exported from uid 10123
>                                                                   at android.os.Parcel.readException(Parcel.java:1684)
>                                                                   at android.os.Parcel.readException(Parcel.java:1637)
>                                                                   at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:4213)
>                                                                   at android.app.ActivityThread.acquireProvider(ActivityThread.java:5526)
>                                                                   at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2239)
>                                                                   at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1517)
>                                                                   at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1131)
>                                                                   at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:984)
>                                                                   at android.content.ContentResolver.openInputStream(ContentResolver.java:704)
>                                                                   at com.whatsapp.util.ah.b(MediaFileUtils.java:1290)
>                                                                   at com.whatsapp.util.ah.a(MediaFileUtils.java:1498)
>                                                                   at com.whatsapp.util.ah.a(MediaFileUtils.java:1543)
>                                                                   at com.whatsapp.gallerypicker.ImagePreview$b$1.a(ImagePreview.java:901)
>                                                                   at com.whatsapp.gallerypicker.ImagePreview$b$1.doInBackground(ImagePreview.java:896)
>                                                                   at android.os.AsyncTask$2.call(AsyncTask.java:305)
>                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
>                                                                   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
>                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
>                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
>                                                                   at java.lang.Thread.run(Thread.java:761) 

I tried the second approach, and it also didn't work. Here's the log from it on Viber (on WhatsApp I don't see anything special) :

> 02-07 09:54:07.084 926-10718/system_process W/ActivityManager: Permission Denial: opening provider com.commonsware.cwac.provider.StreamProvider from ProcessRecord{adbb1ed 5565:com.viber.voip/u0a175} (pid=5565, uid=10175) that is not exported from uid 10123
> 02-07 09:54:07.087 926-10717/system_process W/ActivityManager: Permission Denial: opening provider com.commonsware.cwac.provider.StreamProvider from ProcessRecord{adbb1ed 5565:com.viber.voip/u0a175} (pid=5565, uid=10175) that is not exported from uid 10123
> 02-07 09:54:07.091 926-946/system_process W/ActivityManager: Permission Denial: opening provider com.commonsware.cwac.provider.StreamProvider from ProcessRecord{adbb1ed 5565:com.viber.voip/u0a175} (pid=5565, uid=10175) that is not exported from uid 10123


I've tried now to share a photo from Google Photos to each of those apps. Sure it's not on the resource/assets locations, but it's not on the device either. It works fine there, even though I don't see the files of those photos via the file manager, on "/.../Android/data/com.google.android.apps.photos/..." . 
Somehow it's public to them.

**Comment by AndroidDeveloperLB** [comment]
OK, I've decided to ask this on StackOverflow:

http://stackoverflow.com/q/42084954/878126

**Comment by commonsguy** [comment]
Those errors feel like `FLAG_GRANT_READ_URI_PERMISSION` is missing from the `Intent`. AFAIK, on 7.1.1, if you add that flag, it should affect all `Uri` values in the `ArrayList`.

**Comment by AndroidDeveloperLB** [comment]
How can it be missing?
I didn't remove it. I still see it in the sample.
