### ISSUE TITLE
Share video file from raw.

### ISSUE THREAD

**Issue by AndreNuvi** [commonsguy/cwac-provider#32]
I think cwac-provider is great. Thanks to it I can share internal file. However, I have a problem.
I want to share video from raw folder but I can't do that because there is no explanation or demo how to do it. There is only solution to do it from asset but from asset I can not play video file. I tried various solutions for two days and I give up. My only solution is to duplicate the video resources in raw and assets. In raw to play and in asset to share. This is very space consuming. Can sombebody give me an example or explain how to share video from raw using cwac-provider?

**Comment by commonsguy** [comment]
Um, this is an issue tracker, not a support board. In the future, please use [the support options in the documentation](https://github.com/commonsguy/cwac-provider#questions).

With regards to raw resources, I am not a fan, as I get nervous about the effects of configuration changes. That being said, it is still supported. You can see how it is used in the instrumentation tests, [here](https://github.com/commonsguy/cwac-provider/blob/v0.5.1/provider/src/androidTest/res/xml/paths.xml#L22-L24).
