### ISSUE TITLE
Does it support Storage access framewrok? or does it support for microSD card read/write in some devices?

### ISSUE THREAD

**Issue by softboy99** [commonsguy/cwac-provider#34]
Does it support Storage Access Framework? in some devices, the getExternalStorage**** Api cannot be used and must use Storage Access Framework, how about it?

**Comment by commonsguy** [comment]
This is an issue tracker, not a support board. Please use [the support resources outlined in the documentation](https://github.com/commonsguy/cwac-provider#questions).

> in some devices, the getExternalStorage**** Api cannot be used

AFAIK, all devices support external storage. Some devices may not have any *available* external storage, though that is fairly uncommon.

If you know of some device that does not offer external storage, give me the exact make and model, and I will try to obtain one.

> Does it support Storage Access Framework?

No.

The point behind `StreamProvider` (and `FileProvider`) is to get a `content` `Uri` to some content that does not naturally have its own `Uri`. If you want a `Uri` from the Storage Access Framework, you can get it yourself, via `ACTION_OPEN_DOCUMENT`.
