### ISSUE TITLE
Failed to get type, Permission Denial, Unable to find configured strategy, requires com.google.android.gm.permission.READ_GMAIL

### ISSUE THREAD

**Issue by DaRolla** [commonsguy/cwac-provider#35]
Hi there,

I tried to reproduce your demo. But I am facing some strange issues here.

All I want is to share the PDFs in my assets.

AndroidManifest.xml:

    <provider
        android:name="com.commonsware.cwac.provider.StreamProvider"
        android:authorities="d.a.h.v"
        android:exported="false"
        android:grantUriPermissions="true">
        <meta-data
            android:name="com.commonsware.cwac.provider.STREAM_PROVIDER_PATHS"
            android:resource="@xml/paths"/>
        <meta-data
            android:name="com.commonsware.cwac.provider.USE_LEGACY_CURSOR_WRAPPER"
            android:value="true"/>
        <meta-data
            android:name="com.commonsware.cwac.provider.USE_URI_FOR_DATA_COLUMN"
            android:value="true"/>
    </provider>

paths.xml:

    <?xml version="1.0" encoding="utf-8"?>
    <paths xmlns:android="http://schemas.android.com/apk/res/android">
    
        <asset
            name="in the 'assets' the 'pdfs' folder is shared"
            path="pdfs"/>
    
    </paths>

PdfHelper.java:

    public final class PdfHelper {
    
        private static final String AUTHORITY = "d.a.h.v";
        private static final Uri PROVIDER = Uri.parse("content://" + AUTHORITY);
        private static final String ASSETS = "assets/";
       
        public static Intent getPdfIntent(final String pdfName) {
    
            final String path = ASSETS + pdfName;
    
            final Uri uri = PROVIDER
                    .buildUpon()
                    .appendPath(StreamProvider.getUriPrefix(AUTHORITY))
                    .appendPath(path)
                    .build();
    
            final Intent intent = new Intent(Intent.ACTION_VIEW, uri);
            intent.setFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
            return intent;
        }
    }

Logcat:

    d.a.h.v.fragment.DetailDrugFragment - starting intent: Intent { act=android.intent.action.VIEW dat=content://d.a.h.v/ac0c5618-0f1e-4618-baed-4bdfc3b0f692/assets/Gebrauchsinformation Calmvalera Hevert.pdf flg=0x1 }

    W/ContentResolver: Failed to get type for: content://d.a.h.v/ac0c5618-0f1e-4618-baed-4bdfc3b0f692/assets%2FGebrauchsinformation%20Calmvalera%20Hevert.pdf (Unable to find configured strategy for content://d.a.h.v/assets/Gebrauchsinformation%20Calmvalera%20Hevert.pdf)

    W/ActivityManager: Permission Denial: starting Intent { act=android.intent.action.VIEW dat=content://d.a.h.v/ac0c5618-0f1e-4618-baed-4bdfc3b0f692/assets/Gebrauchsinformation Calmvalera Hevert.pdf flg=0x1 cmp=com.google.android.gm/.browse.TrampolineActivity } from ProcessRecord{d745ec8 14374:d.a.h.v/u0a173} (pid=14374, uid=10173) requires com.google.android.gm.permission.READ_GMAIL

	E/AndroidRuntime: FATAL EXCEPTION: main
	Process: d.a.h.v, PID: 14374
	java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.VIEW dat=content://d.a.h.v/ac0c5618-0f1e-4618-baed-4bdfc3b0f692/assets/Gebrauchsinformation Calmvalera Hevert.pdf flg=0x1 cmp=com.google.android.gm/.browse.TrampolineActivity } from ProcessRecord{d745ec8 14374:d.a.h.v/u0a173} (pid=14374, uid=10173) requires com.google.android.gm.permission.READ_GMAIL
	at android.os.Parcel.readException(Parcel.java:1684)
	at android.os.Parcel.readException(Parcel.java:1637)
	at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:3347)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1690)
	at android.app.Activity.startActivityForResult(Activity.java:4289)
	at android.app.Activity.startActivityForResult(Activity.java:4247)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:820)
	at android.app.Activity.startActivity(Activity.java:4586)
	at android.app.Activity.startActivity(Activity.java:4554)
	at d.a.h.v.fragment.DetailDrugFragment$5.onClick(DetailDrugFragment.java:210)
	at android.view.View.performClick(View.java:5669)
	at android.view.View$PerformClick.run(View.java:22546)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6334)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
	
Best regards,
DaRolla

**Comment by DaRolla** [comment]
by the way: the PDF file has spaces in its name...

**Comment by commonsguy** [comment]
This is an issue tracker. It is not a support board. There are [multiple support options listed in the project documentation](https://github.com/commonsguy/cwac-provider#questions). Please use them.

Use `appendPath()` and `appendEncodedPath()`, rather than `+`, when assembling the `Uri` using the `Uri.Builder`. I don't know if `pdfName` is already encoded or not; I am guessing that it is not. So, that would give you:

        final Uri uri = PROVIDER
                .buildUpon()
                .appendPath(StreamProvider.getUriPrefix(AUTHORITY))
                .appendPath("assets")
                .appendPath(pdfName)
                .build();

**Comment by DaRolla** [comment]
Well, thanks for your response. I think I got the issue. It's the name in the paths.xml:

Using this causes the problems:

    <asset
        name="in the 'assets' the 'pdfs' folder is shared"
        path="pdfs"/>

Using this solves them:

    <asset
        name="assets"
        path="pdfs"/>

I learned (from FileProvider) that the name doesn't matter that much.

So is this an issue or not :-)

Greetings,
DaRolla

**Comment by commonsguy** [comment]
I assumed that was a copy-paste error in the question, and that the `name` was `assets`, since that was what you had in your Java code.

> So is this an issue or not :-)

Well , this does point out that I should add some tests for strange `name` values (spaces, punctuation), and that I should update the docs to point out that `name` values ought to be simple identifiers. I have filed [issue #36](https://github.com/commonsguy/cwac-provider/issues/36) to track that.

Thanks for following up!
